# Generated by Django 4.1.7 on 2023-03-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_animal_options_alter_animaltocrossing_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crossing',
            new_name='Video',
        ),
    ]
