# Generated by Django 4.1.7 on 2023-03-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_animaltocrossing_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
