# Generated by Django 4.1.7 on 2023-05-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_video_name_alter_video_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
